### ISSUE TITLE
oAuth not working with object cache enabled

### ISSUE THREAD

**Issue by laurentvergnaud** [nawawi/docket-cache#13]
Hello, 
We use a single sign on process to log into websites on our hosting platform.
With Docker Object Cache enabled single sign on doesn't work. We are redirected from the wp-admin page to the wp-login page withe reauth=1 even if the logged in cookies are set.
Any idea what could be the issue?

**Comment by nawawi** [comment]
Hi @laurentvergnaud,

You can try excluding user* groups by adding this constant at the wp-config.php file:

`define('DOCKET_CACHE_IGNORED_GROUPS',
  [
    'counts',
    'plugins',
    'themes',
    'user_meta',
    'users', 
    'userlogins',
    'usermeta'
  ]
);`

and flush the object cache.

Thanks.
