### ISSUE TITLE
Doc Has Duplicate Constant

### ISSUE THREAD

**Issue by trinitybranding** [nawawi/docket-cache#14]
Hi.

There is a mistake here in the Docs for these two costants:
![CleanShot 2022-05-16 at 04 17 35@2x](https://user-images.githubusercontent.com/6123260/168549964-7cd78496-35c5-4968-a877-8507c5f4b973.png)

**Comment by nawawi** [comment]
Hi there,

Thank you for reporting this mistake, it has been updated.

Thanks.
