### ISSUE TITLE
Can we open the Discussion tab on this repo?

### ISSUE THREAD

**Issue by abdusfauzi** [nawawi/docket-cache#16]
I would to suggest to open a Discussion tab in this repo, because I have question I want to ask, and not to report a bug or fix.

Question: what is the use of this file?
https://github.com/nawawi/docket-cache/blob/master/includes/compat.php

:D

**Comment by nawawi** [comment]
That file is used to add global functions or any global setup that is outside of the namespace. Also used to add any backwards-compatible functionality.

Yes, we can open a Discussion tab, but currently, our flow support uses the WordPress support forum, which is more centralized.

Thanks.
