### ISSUE TITLE
Object cache class: missing magic getter/setter?

### ISSUE THREAD

**Issue by thomascharbit** [nawawi/docket-cache#20]
Hi,

The default `WP_Object_Cache` class [has some magic methods ](https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-includes/class-wp-object-cache.php#L85-L131)for getting/setting private properties.

It looks like Docket Cache `WP_Object_Cache` implementation doesnt provide them.

This results in a fatal errors when trying to access these private properties.

I encountered the issue with WooCommerce which is using Async Scheduler.
When memory is getting full, Async Scheduler tries to free some memory by [clearing some object cache properties](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/ActionScheduler_DataController.php#L151-L154).

I originally opened an issue on the [Async Scheduler repo](https://github.com/woocommerce/action-scheduler/issues/1008), but shouldn't they be implemented as they are in the core `WP_Object_Cache` class?

thanks

**Comment by nawawi** [comment]
Hi @thomascharbit ,

Yes, Docket Cache doesn't provide that implementation. You may download the fix file here https://docketcache.com/devtest/docket-cache-230802-rc1.zip

Thanks.

**Comment by thomascharbit** [comment]
Awesome, thanks!
