### ISSUE TITLE
Opt-out of Automatic Plugin Updates

### ISSUE THREAD

**Issue by JLHC** [nawawi/docket-cache#7]
Hi,

I can't seem to opt-out of Automatic Plugin Updates for Docket Cache. 

I like to test all my plugin updates in my staging environment before deploying them to live. 

Appreciate if this can be made easier. 

Thank you.

**Comment by nawawi** [comment]
Hi there,

goto Configuration -> "Docket Cache Auto-Updates" and select "Disable"

![DCAU](https://user-images.githubusercontent.com/1203635/102780244-8cd59c00-43d0-11eb-8431-79648c6d27fd.png)


Thanks.

**Comment by JLHC** [comment]
Thanks for pointing that out!

Hope you'll make it easier by respecting the option to deactivate auto plugin updates directly within the Plugins page.

**Comment by nawawi** [comment]
Hi,

We're using WordPress filter hook "auto_update_plugin", currently this is the way how it works. I will try to change in the next release.

I'm closing this issue.

Thanks.
